#!/bin/bash

# PM2 commands for spirit-bead-designs application

echo "Available PM2 commands:"
echo ""
echo "Start the application:"
echo "pm2 start ecosystem.config.js"
echo ""
echo "Start in production mode:"
echo "pm2 start ecosystem.config.js --env production"
echo ""
echo "View running processes:"
echo "pm2 list"
echo ""
echo "View logs:"
echo "pm2 logs spirit-bead-designs"
echo ""
echo "Stop the application:"
echo "pm2 stop spirit-bead-designs"
echo ""
echo "Restart the application:"
echo "pm2 restart spirit-bead-designs"
echo ""
echo "Delete the application from PM2:"
echo "pm2 delete spirit-bead-designs"
echo ""
echo "Monitor the application:"
echo "pm2 monit"
echo ""
echo "Save PM2 configuration (auto-start on server reboot):"
echo "pm2 save"
echo "pm2 startup"
